RES-159 modified,added 特徴量計算のI/F変更、テスト追加
リファクタリング、品質向上

diff --git a/test_data/Makefile b/test_data/Makefile
--- a/test_data/Makefile
+++ b/test_data/Makefile
@@ -1,77 +1,12 @@
 
 SEMICRF=../semicrf
 
-all:
-# 0,1,2,3
-#	$(SEMICRF) -t test0.txt --debug > result0.txt && diff answer/result0.txt result0.txt && echo "OK" || echo "ERROR"
-#	$(SEMICRF) -i test1.txt --debug > result1.txt && diff answer/result1.txt result1.txt && echo "OK" || echo "ERROR"
-# 4
-	@echo "###### TEST 4 ######"
-	@$(SEMICRF) -t test4.txt -w weight4.txt --log-level 2 --max-length 1 -e0 1.0e-1 --max-iteration 10 --disable-adagrad --disable-date-version 1> result4.txt 2>&1 && echo "OK" || echo "ERROR"
-	@diff answer/result4.txt result4.txt && echo "OK" || echo "ERROR"
-	@diff answer/weight4.txt weight4.txt && echo "OK" || echo "ERROR"
-# 5
-	@echo "###### TEST 5 ######"
-	@$(SEMICRF) -t test4.txt -w weight5.txt --log-level 2 --max-length 2 -e0 1.0e-1 --max-iteration 5 --disable-adagrad --disable-date-version 1> result5.txt 2>&1 && echo "OK" || echo "ERROR"
-	@diff answer/result5.txt result5.txt && echo "OK" || echo "ERROR"
-	@diff answer/weight5.txt weight5.txt && echo "OK" || echo "ERROR"
-# 6
-	@echo "###### TEST 6 ######"
-	@$(SEMICRF) -i test6.txt -w answer/weight4.txt --log-level 0 --max-length 1 --disable-date-version 1> result6.txt 2>&1 && echo "OK" || echo "ERROR"
-	@diff answer/result6.txt result6.txt && echo "OK" || echo "ERROR"
-# 7
-	@echo "###### TEST 7 ######"
-	@$(SEMICRF) -t test4.txt -w weight7.txt --log-level 1 --max-length 1 -e0 1.0e-1 -e1 0.5e-1 --max-iteration 1024 --disable-adagrad --disable-date-version 1> result7.txt 2>&1 && echo "OK" || echo "ERROR"
-	@diff answer/result7.txt result7.txt && echo "OK" || echo "ERROR"
-	@diff answer/weight7.txt weight7.txt && echo "OK" || echo "ERROR"
-# 8
-	@echo "###### TEST 8 ######"
-	@$(SEMICRF) -t test8.txt -w weight8.txt --log-level 1 --max-length 2 -e0 1.0e-1 -e1 1.0e-2 --disable-adagrad --disable-date-version 1> result8.txt 2>&1 && echo "OK" || echo "ERROR"
-	@diff answer/result8.txt result8.txt && echo "OK" || echo "ERROR"
-	@diff answer/weight8.txt weight8.txt && echo "OK" || echo "ERROR"
-# 9
-	@echo "###### TEST 9 ######"
-	@$(SEMICRF) -i test9.txt -w answer/weight8.txt --log-level 0 --max-length 2 --disable-date-version 1> result9.txt 2>&1 && echo "OK" || echo "ERROR"
-	@diff answer/result9.txt result9.txt && echo "OK" || echo "ERROR"
-# 10
-	@echo "###### TEST 10 ######"
-	@$(SEMICRF) -t test10.txt -w weight10.txt --log-level 0 --max-length 1 -e0 1.0e-1 -e1 1.0e-2 --disable-adagrad --disable-date-version 1> result10.txt 2>&1 && echo "OK" || echo "ERROR"
-	@diff answer/result10.txt result10.txt && echo "OK" || echo "ERROR"
-	@diff answer/weight10.txt weight10.txt && echo "OK" || echo "ERROR"
-# 11
-	@echo "###### TEST 11 ######"
-	@$(SEMICRF) -i test11.txt -w answer/weight10.txt --log-level 0 --max-length 1 --disable-date-version 1> result11.txt 2>&1 && echo "OK" || echo "ERROR"
-	@diff answer/result11.txt result11.txt && echo "OK" || echo "ERROR"
-# 12
-	@echo "###### TEST 12 ######"
-	@$(SEMICRF) -t test12.txt -w weight12.txt --log-level 0 --max-length 2 -e0 1.0e-1 -e1 1.0e-2 --disable-adagrad 1> result12.txt 2>&1 && echo "OK" || echo "ERROR"
-	@diff answer/result12.txt result12.txt && echo "OK" || echo "ERROR"
-	@diff answer/weight12.txt weight12.txt && echo "OK" || echo "ERROR"
-# 13
-	@echo "###### TEST 13 ######"
-	@$(SEMICRF) -i test13.txt -w answer/weight12.txt --log-level 0 --max-length 2 --disable-date-version 1> result13.txt 2>&1 && echo "OK" || echo "ERROR"
-	@diff answer/result13.txt result13.txt && echo "OK" || echo "ERROR"
-# 14
-	@echo "###### TEST 14 ######"
-	@$(SEMICRF) -t test14.txt -w weight14.txt --log-level 0 --max-length 2 -e0 1.0e-1 -e1 1.0e-2 --disable-adagrad --disable-date-version 1> result14.txt 2>&1 && echo "OK" || echo "ERROR"
-	@diff answer/result14.txt result14.txt && echo "OK" || echo "ERROR"
-	@diff answer/weight14.txt weight14.txt && echo "OK" || echo "ERROR"
-# 15
-	@echo "###### TEST 15 ######"
-	@$(SEMICRF) -i test15.txt -w answer/weight14.txt --log-level 0 --max-length 2 --disable-date-version 1> result15.txt 2>&1 && echo "OK" || echo "ERROR"
-	@diff answer/result15.txt result15.txt && echo "OK" || echo "ERROR"
-# 16
-	@echo "###### TEST 16 ######"
-	@$(SEMICRF) -i test16.txt -w answer/weight16.txt --log-level 0 --max-length 2 --disable-date-version 1> result16.txt 2>&1 && echo "OK" || echo "ERROR"
-	@diff answer/result16.txt result16.txt && echo "OK" || echo "ERROR"
-# 17
-	@echo "###### TEST 17 ######"
-	@$(SEMICRF) -i test17.txt -w answer/weight17.txt --log-level 2 --max-length 32 --disable-date-version 1> result17.txt 2>&1 && echo "OK" || echo "ERROR"
-	@diff answer/result17.txt result17.txt && echo "OK" || echo "ERROR"
-# 18
-	@echo "###### TEST 18 ######"
-	@$(SEMICRF) -i test18.txt -w answer/weight18.txt --log-level 2 --max-length 32 --disable-date-version 1> result18.txt 2>&1 && echo "OK" || echo "ERROR"
-	@diff answer/result18.txt result18.txt && echo "OK" || echo "ERROR"
+all: test1 test2
+
+test1:
+	@echo "###### check0 ######"
+	$(SEMICRF) -t check1 -w tmp1 --log-level 2 -e0 2.0 -e1 1.0e-5 --max-iteration 100000 --disable-date-version 2>log1 
+	@diff answer/log1 log1 && echo "OK" || echo "ERROR"
 
 FILES0=\
 	check1 \
@@ -80,7 +15,7 @@ FILES0=\
 	check4 \
 	check5
 
-check:
+test2:
 	@for file in $(FILES0); do \
 		echo "###### $$file ######"; \
 		echo "$(SEMICRF) -t $$file -w tmp1 --log-level 0 -e0 2.0 -e1 1.0e-5 --max-iteration 100000"; \
