RES-1201 modify 職種の辞書を追加

diff --git a/test_data/Makefile b/test_data/Makefile
--- a/test_data/Makefile
+++ b/test_data/Makefile
@@ -2,7 +2,8 @@
 CONTAINER_NAME=cicada_container
 
 SEMICRF=../semicrf
-DIC=../dic/Noun.place.utf8.csv
+AREA_DIC=../dic/Noun.place.utf8.csv
+JOB_DIC=../dic/job.txt
 
 all: test1 test2 test3 test4 test5 learn infer gen_test bd2c_test bd2w_test bdc2e_test
 
@@ -40,15 +41,15 @@ FILES1=check6.json
 MATRIX=../../word2vec/wakati.bin
 
 test3:
-	time $(SEMICRF) -t ${FILES1} -w tmp1 --log-level 2 -e0 1.0e-6 -e1 1.0e-3 --regularization-parameter 1e-8 --w2v-matrix ${MATRIX} -a ${DIC} && echo "OK" || echo "ERROR"
-	$(SEMICRF) -i ${FILES1} -w tmp1 --log-level 3 --w2v-matrix ${MATRIX} -a ${DIC} > tmp2 && echo "OK" || echo "ERROR"
+	time $(SEMICRF) -t ${FILES1} -w tmp1 --log-level 2 -e0 1.0e-6 -e1 1.0e-3 --regularization-parameter 1e-8 --w2v-matrix ${MATRIX} -a ${AREA_DIC} -j ${JOB_DIC} && echo "OK" || echo "ERROR"
+	$(SEMICRF) -i ${FILES1} -w tmp1 --log-level 3 --w2v-matrix ${MATRIX} -a ${AREA_DIC} -j ${JOB_DIC} > tmp2 && echo "OK" || echo "ERROR"
 	jq '.pages[].data[][][2]' ${FILES1} > r1
 	jq '.pages[].data[][][2]' tmp2 > r2
 	echo "diff -c r1 r2"
 	diff -c r1 r2 && echo "OK" || echo "ERROR"
-	$(SEMICRF) -i ${FILES1} -w tmp1 --log-level 3 --w2v-matrix ${MATRIX} -a ${DIC} --enable-simple-prediction-output > simple_output3.json && echo "OK" || echo "ERROR"
+	$(SEMICRF) -i ${FILES1} -w tmp1 --log-level 3 --w2v-matrix ${MATRIX} -a ${AREA_DIC} -j ${JOB_DIC} --enable-simple-prediction-output > simple_output3.json && echo "OK" || echo "ERROR"
 	diff -c answer/simple_output3.json simple_output3.json && echo "OK" || echo "ERROR"
-	$(SEMICRF) -i check10.json -w tmp1 --log-level 3 --w2v-matrix ${MATRIX} -a ${DIC} --enable-simple-prediction-output > check10_output.json && echo "OK" || echo "ERROR"
+	$(SEMICRF) -i check10.json -w tmp1 --log-level 3 --w2v-matrix ${MATRIX} -a ${AREA_DIC} -j ${JOB_DIC} --enable-simple-prediction-output > check10_output.json && echo "OK" || echo "ERROR"
 	diff -c answer/check10_output.json check10_output.json && echo "OK" || echo "ERROR"
 	rm tmp1 tmp2
 
@@ -56,30 +57,30 @@ test3:
 FILES2=check12.json
 
 test4:
-	time $(SEMICRF) -t ${FILES2} -w tmp1 --log-level 2 -e0 1.0e-6 -e1 1.0e-4 --regularization-parameter 1e-8 --w2v-matrix ${MATRIX} -a ${DIC} && echo "OK" || echo "ERROR"
-	$(SEMICRF) -i ${FILES2} -w tmp1 --log-level 3 --w2v-matrix ${MATRIX} -a ${DIC} > tmp2 && echo "OK" || echo "ERROR"
+	time $(SEMICRF) -t ${FILES2} -w tmp1 --log-level 2 -e0 1.0e-6 -e1 1.0e-4 --regularization-parameter 1e-8 --w2v-matrix ${MATRIX} -a ${AREA_DIC} -j ${JOB_DIC} && echo "OK" || echo "ERROR"
+	$(SEMICRF) -i ${FILES2} -w tmp1 --log-level 3 --w2v-matrix ${MATRIX} -a ${AREA_DIC} -j ${JOB_DIC} > tmp2 && echo "OK" || echo "ERROR"
 	jq '.pages[].data[][][2]' ${FILES2} > r1
 	jq '.pages[].data[][][2]' tmp2 > r2
 	echo "diff -c r1 r2"
 	diff -c r1 r2 && echo "OK" || echo "ERROR"
-	$(SEMICRF) -i ${FILES2} -w tmp1 --log-level 3 --w2v-matrix ${MATRIX} -a ${DIC} --enable-simple-prediction-output > simple_output4.json && echo "OK" || echo "ERROR"
+	$(SEMICRF) -i ${FILES2} -w tmp1 --log-level 3 --w2v-matrix ${MATRIX} -a ${AREA_DIC} -j ${JOB_DIC} --enable-simple-prediction-output > simple_output4.json && echo "OK" || echo "ERROR"
 	diff -c answer/simple_output4.json simple_output4.json && echo "OK" || echo "ERROR"
-	$(SEMICRF) -i check13.json -w tmp1 --log-level 3 --w2v-matrix ${MATRIX} -a ${DIC} --enable-simple-prediction-output > check13_output.json && echo "OK" || echo "ERROR"
+	$(SEMICRF) -i check13.json -w tmp1 --log-level 3 --w2v-matrix ${MATRIX} -a ${AREA_DIC} -j ${JOB_DIC} --enable-simple-prediction-output > check13_output.json && echo "OK" || echo "ERROR"
 	diff -c answer/check13_output.json check13_output.json && echo "OK" || echo "ERROR"
 	rm tmp1 tmp2
 
 FILES3=check14.json
 
 test5:
-	time $(SEMICRF) -t ${FILES3} -w tmp1 --log-level 2 -e0 1.0e-6 -e1 1.0e-3 --regularization-parameter 1e-8 --w2v-matrix ${MATRIX} -a ${DIC} && echo "OK" || echo "ERROR"
-	$(SEMICRF) -i ${FILES3} -w tmp1 --log-level 3 --w2v-matrix ${MATRIX} -a ${DIC} > tmp2 && echo "OK" || echo "ERROR"
+	time $(SEMICRF) -t ${FILES3} -w tmp1 --log-level 2 -e0 1.0e-6 -e1 1.0e-3 --regularization-parameter 1e-8 --w2v-matrix ${MATRIX} -a ${AREA_DIC} -j ${JOB_DIC} && echo "OK" || echo "ERROR"
+	$(SEMICRF) -i ${FILES3} -w tmp1 --log-level 3 --w2v-matrix ${MATRIX} -a ${AREA_DIC} -j ${JOB_DIC} > tmp2 && echo "OK" || echo "ERROR"
 	jq '.pages[].data[][][2]' ${FILES3} > r1
 	jq '.pages[].data[][][2]' tmp2 > r2
 	echo "diff -c r1 r2"
 	diff -c r1 r2 && echo "OK" || echo "ERROR"
-#	$(SEMICRF) -i ${FILES3} -w tmp1 --log-level 3 --w2v-matrix ${MATRIX} -a ${DIC} --enable-simple-prediction-output > simple_output4.json && echo "OK" || echo "ERROR"
+#	$(SEMICRF) -i ${FILES3} -w tmp1 --log-level 3 --w2v-matrix ${MATRIX} -a ${AREA_DIC} -j ${JOB_DIC} --enable-simple-prediction-output > simple_output4.json && echo "OK" || echo "ERROR"
 #	diff -c answer/simple_output4.json simple_output4.json && echo "OK" || echo "ERROR"
-#	$(SEMICRF) -i check13.json -w tmp1 --log-level 3 --w2v-matrix ${MATRIX} -a ${DIC} --enable-simple-prediction-output > check13_output.json && echo "OK" || echo "ERROR"
+#	$(SEMICRF) -i check13.json -w tmp1 --log-level 3 --w2v-matrix ${MATRIX} -a ${AREA_DIC} -j ${JOB_DIC} --enable-simple-prediction-output > check13_output.json && echo "OK" || echo "ERROR"
 #	diff -c answer/check13_output.json check13_output.json && echo "OK" || echo "ERROR"
 #	rm tmp1 tmp2
 
