RES-1054 modify "地名"だけに特化した素性の実装

diff --git a/test_data/Makefile b/test_data/Makefile
--- a/test_data/Makefile
+++ b/test_data/Makefile
@@ -4,7 +4,7 @@ CONTAINER_NAME=cicada_container
 SEMICRF=../semicrf
 DIC=../../src/mecab/mecab-ipadic-2.7.0-20070801/Noun.place.utf8.csv
 
-all: test1 test2 test3 test4 learn infer gen_test bd2c_test bd2w_test bdc2e_test
+all: test1 test2 test3 learn infer gen_test bd2c_test bd2w_test bdc2e_test
 
 test1:
 	@echo "###### check0 ######"
@@ -40,28 +40,17 @@ FILES1=check6.json
 MATRIX=../../word2vec/wakati.bin
 
 test3:
-	time $(SEMICRF) -t ${FILES1} -w tmp1 --log-level 2 -e0 1.0e-6 -e1 1.0e-3 --regularization-parameter 1e-6 --w2v-matrix ${MATRIX} -a ${DIC} && echo "OK" || echo "ERROR"
+	time $(SEMICRF) -t ${FILES1} -w tmp1 --log-level 2 -e0 1.0e-6 -e1 1.0e-4 --regularization-parameter 1e-8 --w2v-matrix ${MATRIX} -a ${DIC} && echo "OK" || echo "ERROR"
 	$(SEMICRF) -i ${FILES1} -w tmp1 --log-level 3 --w2v-matrix ${MATRIX} -a ${DIC} > tmp2 && echo "OK" || echo "ERROR"
-	jq '.pages[].data[][][]' ${FILES1} > r1
-	jq '.pages[].data[][][]' tmp2 > r2
-	cat r1 | awk '{ if(k++ % 4 == 2) print $$1 }' > a
-	cat r2 | awk '{ if(k++ % 4 == 2) print $$1 }' > b
-	echo "diff -c a b"
-	diff -c a b && echo "OK" || echo "ERROR"
-	paste a b | awk '{ if( $$1 == $$2 ) count++; total++; } END{ print count/total*100,"%"; }'
+	jq '.pages[].data[][][2]' ${FILES1} > r1
+	jq '.pages[].data[][][2]' tmp2 > r2
+	echo "diff -c r1 r2"
+	diff -c r1 r2 && echo "OK" || echo "ERROR"
 	$(SEMICRF) -i ${FILES1} -w tmp1 --log-level 3 --w2v-matrix ${MATRIX} -a ${DIC} --enable-simple-prediction-output > simple_output.json && echo "OK" || echo "ERROR"
 	diff -c answer/simple_output.json simple_output.json && echo "OK" || echo "ERROR"
 	$(SEMICRF) -i check10.json -w tmp1 --log-level 3 --w2v-matrix ${MATRIX} -a ${DIC} --enable-simple-prediction-output > check10_output.json && echo "OK" || echo "ERROR"
 	diff -c answer/check10_output.json check10_output.json && echo "OK" || echo "ERROR"
 	rm tmp1 tmp2
-
-FILES2=check7.json
-
-test4:
-	time $(SEMICRF) -t ${FILES2} -w tmp1 --log-level 2 -e0 1.0e-6 -e1 1.0e-3 --regularization-parameter 1e-6 --w2v-matrix ${MATRIX} -a ${DIC} && echo "OK" || echo "ERROR"
-	$(SEMICRF) -i check10.json -w tmp1 --log-level 3 --w2v-matrix ${MATRIX} -a ${DIC} --enable-simple-prediction-output > check11_output.json && echo "OK" || echo "ERROR"
-	diff -c answer/check11_output.json check11_output.json && echo "OK" || echo "ERROR"
-	rm tmp1
 
 learn:
 	../gen -i p0.json -r 32 -l 16 > tmp1
