RES-265 modified,added bdc2e実装、テスト追加

diff --git a/test_data/Makefile b/test_data/Makefile
--- a/test_data/Makefile
+++ b/test_data/Makefile
@@ -47,10 +47,14 @@ test3:
 		cat $$file | jq '.data[][][]' > r1; \
 		cat tmp2 | jq '.data[][][]' > r2; \
 		cat r1 | awk '{ if(k++ % 4 == 2) print $$1 }' > a; \
-		cat r2 | awk '{ if(k++ % 3 == 2) print $$1 }' > b; \
+		cat r2 | awk '{ if(k++ % 4 == 2) print $$1 }' > b; \
 		echo "diff -c a b"; \
 		diff -c a b && echo "OK" || echo "ERROR"; \
 		paste a b | awk '{ if( $$1 == $$2 ) count++; total++; } END{ print count/total*100,"%"; }'; \
+		echo "../bdc2e -c tmp2"; \
+		../bdc2e -c tmp2 > bdc2e.json && echo "OK" || echo "ERROR"; \
+		echo "diff -c answer/bdc2e.json bdc2e.json"; \
+		diff -c answer/bdc2e.json bdc2e.json && echo "OK" || echo "ERROR"; \
 		rm tmp1 tmp2; \
 	done;
 
@@ -112,6 +116,7 @@ update:
 	-cp test18.json answer/test18.json
 	-cp test19.json answer/test19.json
 	-cp body1.txt answer/body1.txt
+	-cp bdc2e.json answer/bdc2e.json
 
 clean:
 	rm -f a b r1 r2 tmp* log1 check8.json
